using FluentValidation;
using Microsoft.Extensions.DependencyInjection;
using ProjectManagement.Application.Abstractions;
using ProjectManagement.Application.Common;
using ProjectManagement.Application.Features.Admin;
using ProjectManagement.Application.Features.Auth;
using ProjectManagement.Application.Features.Automation;
using ProjectManagement.Application.Features.Reports;
using ProjectManagement.Application.Features.Time;
using ProjectManagement.Application.Features.Billing;
using ProjectManagement.Application.Features.Configuration;
using ProjectManagement.Application.Features.Files;
using ProjectManagement.Application.Features.Insights;
using ProjectManagement.Application.Features.Issues;
using ProjectManagement.Application.Features.Import;
using ProjectManagement.Application.Features.Integrations;
using ProjectManagement.Application.Features.Notifications;
using ProjectManagement.Application.Features.Organization;
using ProjectManagement.Application.Features.Planning;
using ProjectManagement.Application.Features.Projects;
using ProjectManagement.Application.Features.Tasks;
using ProjectManagement.Application.Features.Teams;
using ProjectManagement.Application.Features.Workspaces;
using ProjectManagement.Application.Services;

namespace ProjectManagement.Application;

public static class DependencyInjection
{
    public static IServiceCollection AddApplication(this IServiceCollection services)
    {
        // One mutable context per request/scope; ICurrentContext is the read-only view services depend on.
        services.AddScoped<CurrentContext>();
        services.AddScoped<ICurrentContext>(sp => sp.GetRequiredService<CurrentContext>());

        services.AddScoped<ProjectManagement.Application.Features.Ai.AiDatabaseTelemetry>();
        services.AddScoped<ProjectManagement.Application.Features.Ai.AiCommandPlanner>();
        services.AddScoped<ProjectManagement.Application.Features.Ai.AiRequestLimitService>();
        services.AddScoped<AppClock>();
        services.AddScoped<Recorder>();
        services.AddScoped<PermissionService>();
        services.AddScoped<EntitlementService>();
        services.AddScoped<ProjectAccess>();
        services.AddScoped<WorkspaceProvisioner>();

        services.AddScoped<SecurityAlerts>();
        services.AddScoped<MfaService>();
        services.AddScoped<PasswordPolicyService>();
        services.AddScoped<ProjectManagement.Application.Features.Organization.OrgSecurityService>();
        services.AddScoped<ProjectManagement.Application.Features.Consent.ConsentService>();
        services.AddScoped<AuthService>();
        services.AddScoped<DeviceLoginService>();
        services.AddScoped<PasskeyService>();
        services.AddScoped<ProjectManagement.Application.Features.Billing.InvoiceService>();
        services.AddScoped<ProjectManagement.Application.Features.Billing.SubscriptionActivator>();
        services.AddScoped<ProjectManagement.Application.Features.Billing.BillingWebhookService>();
        services.AddScoped<EmailRetryService>();
        services.AddScoped<EmailLinks>();
        services.AddScoped<UnsubscribeService>();
        services.AddScoped<EmailAdminService>();
        services.AddScoped<ProjectManagement.Application.Features.Sso.SsoPolicy>();
        services.AddScoped<ProjectManagement.Application.Features.Sso.SsoSettingsService>();
        services.AddScoped<ProjectManagement.Application.Features.Sso.SsoLoginService>();
        services.AddScoped<ProjectManagement.Application.Features.Sso.ScimService>();
        services.AddScoped<WorkspaceService>();
        services.AddScoped<TeamService>();
        services.AddScoped<ProjectManagement.Application.Features.Documents.DocumentService>();
        services.AddScoped<ProjectManagement.Application.Features.Documents.DocumentLinkService>();
        services.AddScoped<ProjectManagement.Application.Features.Documents.DocumentAccessService>();
        services.AddScoped<ProjectManagement.Application.Features.Documents.DocumentVersionService>();
        services.AddScoped<ProjectManagement.Application.Features.Documents.DocumentFileService>();
        services.AddScoped<ProjectManagement.Application.Features.Documents.DocumentRetentionService>();
        services.AddScoped<ProjectManagement.Application.Features.Documents.DocumentNotifier>();
        services.AddScoped<ProjectManagement.Application.Features.Documents.DocumentWorkflowService>();
        services.AddScoped<ProjectManagement.Application.Features.Documents.DocumentAccessRequestService>();
        services.AddScoped<ProjectManagement.Application.Features.Documents.DocumentTraceService>();
        services.AddScoped<ProjectManagement.Application.Features.Documents.DocumentAuditService>();
        services.AddScoped<ProjectManagement.Application.Features.Integrations.GoogleCalendarAuthService>();
        services.AddScoped<ProjectManagement.Application.Features.Integrations.GoogleMeetingClient>();
        services.AddScoped<ProjectManagement.Application.Features.ProjectMeetings.MeetingService>();
        services.AddScoped<ProjectManagement.Application.Features.ProjectMeetings.MeetingSyncEngine>();
        services.AddSingleton<ProjectManagement.Application.Features.Documents.IDocumentPdfRenderer, ProjectManagement.Application.Features.Documents.DocumentPdfRenderer>();
        services.AddScoped<ProjectManagement.Application.Features.Documents.DocumentPdfBuilder>();
        services.AddScoped<ProjectManagement.Application.Features.Documents.DocumentPdfJob>();
        services.AddScoped<ProjectManagement.Application.Features.Documents.DocumentExportService>();
        services.AddScoped<ProjectManagement.Application.Features.Documents.DocumentSearchIndexer>();
        services.AddScoped<ProjectManagement.Application.Features.Documents.DocumentDashboardService>();
        services.AddScoped<ProjectManagement.Application.Features.Sso.SsoGroupMappingService>();
        services.AddScoped<ProjectManagement.Application.Features.Workspaces.WorkspaceLogoService>();
        services.AddScoped<ProjectManagement.Application.Features.People.MemberProfileService>();
        services.AddScoped<ProjectManagement.Application.Features.People.UserAvatarService>();
        services.AddScoped<ProjectManagement.Application.Features.Documents.EnvelopeCrypto>();
        services.AddScoped<ProjectManagement.Application.Features.Documents.StepUpService>();
        services.AddScoped<ProjectManagement.Application.Features.Documents.SecretService>();
        services.AddScoped<ProjectManagement.Application.Features.Documents.AuditChainService>();
        services.AddScoped<ProjectManagement.Application.Features.Documents.KeyRotationService>();
        services.AddScoped<ProjectManagement.Application.Features.Documents.DocumentSecurityService>();
        services.AddScoped<ProjectManagement.Application.Features.Documents.DocumentInboxService>();
        services.AddScoped<ProjectManagement.Application.Features.ApiDocs.ApiDocService>();
        services.AddScoped<ProjectManagement.Application.Features.ApiDocs.ApiTransferService>();
        services.AddScoped<OrgService>();
        services.AddScoped<AccessService>();
        services.AddScoped<ProjectService>();
        services.AddScoped<DueDateHistory>();
        services.AddScoped<ProjectGroupService>();
        services.AddScoped<ProjectStatusService>();
        services.AddScoped<ActionItemService>();
        services.AddScoped<ProjectManagement.Application.Features.Work.WorkTypeService>();
        services.AddScoped<ProjectManagement.Application.Features.Work.WorkTaskService>();
        services.AddScoped<ProjectManagement.Application.Features.Work.SlaService>();
        services.AddScoped<ProjectManagement.Application.Features.Work.SlaMonitor>();
        services.AddScoped<ProjectManagement.Application.Features.WorkItems.WorkItemService>();
        services.AddScoped<ProjectManagement.Application.Features.WorkItems.WorkloadService>();
        services.AddScoped<TaskService>();
        services.AddScoped<TaskCompletionService>();
        services.AddScoped<IssueService>();
        services.AddScoped<TimelineTemplateService>();
        services.AddScoped<PlanningService>();
        services.AddScoped<TimeService>();
        services.AddScoped<TimesheetApprovalService>();
        services.AddScoped<CapacityService>();
        services.AddScoped<ProjectManagement.Application.Features.Integrations.CalendarFeedService>();
        services.AddScoped<ProjectManagement.Application.Features.Integrations.InboundEmailService>();
        services.AddScoped<ProjectManagement.Application.Features.Integrations.GitLinkService>();
        services.AddScoped<ProjectManagement.Application.Features.Compliance.DataPolicyService>();
        services.AddScoped<ProjectManagement.Application.Features.Compliance.WorkspaceExporter>();
        services.AddScoped<ProjectManagement.Application.Features.Ai.AiAssistant>();
        // The AI workspace: conversations, the tools it reads the workspace with, the changes it proposes, and attached files.
        services.AddScoped<ProjectManagement.Application.Features.Ai.AiToolbox>();
        services.AddScoped<ProjectManagement.Application.Features.Ai.AiActionRunner>();
        services.AddScoped<ProjectManagement.Application.Features.Ai.AiFileService>();
        services.AddScoped<ProjectManagement.Application.Features.Ai.AiGuidance>();
        services.AddScoped<ProjectManagement.Application.Features.Ai.AiAnalysis>();
        services.AddScoped<ProjectManagement.Application.Features.Ai.AiPortfolio>();
        services.AddScoped<ProjectManagement.Application.Features.Ai.AiAgent>();
        services.AddScoped<ProjectManagement.Application.Features.Ai.AiUsageService>();
        services.AddScoped<ProjectManagement.Application.Features.Ai.AgentTrackerService>();
        services.AddScoped<ProjectManagement.Application.Features.Automation.AutomationScheduler>();
        services.AddScoped<ProjectManagement.Application.Features.Notifications.PushService>();
        services.AddScoped<ProjectManagement.Application.Features.Reminders.ReminderService>();
        services.AddScoped<ProjectManagement.Application.Features.Reminders.ReminderEngine>();
        services.AddScoped<ProjectManagement.Application.Features.Reminders.PortfolioDigestService>();
        services.AddScoped<ProjectManagement.Application.Features.Reminders.ReminderPlanner>();
        services.AddScoped<ProjectManagement.Application.Features.Reminders.ReminderActionService>();
        services.AddSingleton<ProjectManagement.Application.Features.Reminders.ReminderMetrics>();
        services.AddScoped<ProjectManagement.Application.Features.Chat.ChatService>();
        services.AddScoped<PlatformService>();
        services.AddScoped<GoLiveService>();
        services.AddSingleton<PlatformSettingsCache>();
        services.AddSingleton<SystemMetrics>();
        services.AddSingleton<WorkerHeartbeats>();
        services.AddScoped<ReportingLineService>();
        services.AddScoped<WebhookService>();
        services.AddSingleton<WebhookProcessor>();
        services.AddScoped<ApiKeyService>();
        services.AddScoped<ApiKeyAuthenticator>();
        services.AddScoped<CustomFieldService>();
        services.AddScoped<TaskImportService>();
        services.AddScoped<ChecklistService>();
        services.AddScoped<PriorityService>();
        services.AddScoped<ReportExportService>();
        services.AddScoped<ReportBuilder>();
        services.AddSingleton<ReportExportProcessor>();
        services.AddScoped<SprintService>();
        services.AddScoped<AutomationService>();
        services.AddScoped<AutomationEngine>();
        services.AddScoped<AttachmentService>();
        services.AddScoped<AttachmentJanitor>();
        services.AddScoped<NotificationRouter>();
        services.AddScoped<NotificationService>();
        services.AddScoped<NotificationPreferenceService>();
        services.AddScoped<NotificationEmailService>();
        services.AddScoped<ActivityService>();
        services.AddScoped<DashboardService>();
        services.AddScoped<CalendarService>();
        services.AddScoped<SearchService>();
        services.AddScoped<ReportService>();
        services.AddScoped<BillingService>();
        services.AddScoped<MaintenanceService>();
        services.AddScoped<AdminService>();

        services.AddValidatorsFromAssemblyContaining<RegisterRequest>(includeInternalTypes: true);
        return services;
    }
}
